
- name: check if qxl module is loaded in kernel
  shell: lsmod | grep "^{{ disable_qxl_module_name }} "
  changed_when: false
  failed_when: false
  register: disable_qxl_lsmod_output
  
- include_tasks: disable-qxl.yml
  when: not disable_qxl_lsmod_output.rc

