
- name: check if qxl module is loaded in kernel
  shell: lsmod | grep "^{{ kypo_disable_qxl_module_name }} "
  changed_when: false
  failed_when: false
  register: kypo_disable_qxl_lsmod_output
  
- include: disable-qxl.yml
  when: not kypo_disable_qxl_lsmod_output.rc

